version: "3"
services:

  plan:
    image: hashicorp/terraform
    environment:
      - TF_INPUT=0
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/workdir
      - /usr/local/var/buildkite-agent/builds/:/usr/local/var/buildkite-agent/builds/
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/plan.sh"

  apply:
    image: hashicorp/terraform
    environment:
      - TF_INPUT=0
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/workdir
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/apply.sh"