name: Test
description: test plugin
author: https://github.com/elahehgh
requirements:
  - terraform
  - bash
  - aws
configuration:
  properties:
    bucket:
      type: string
  required:
    - bucket