#!/usr/bin/env bash

echo   "running test plugin pre-command hook to build a bucket ${BUILDKITE_PLUGIN_TEST_BUCKET}"

set -xe

cat > main.tf << EOF
terraform {
  backend "s3" {
    key    = "terraform/test"
    region = "ap-southeast-2"
  }
}

provider "aws" {
  region = "ap-southeast-2"
}

resource "aws_s3_bucket" "test" {
  bucket = "elaheh-test-bucket"
}
EOF

echo "+++ :terraform: Terraform Init"

terraform init \
    -backend-config="bucket=terraform-tfstate-elaheh"
echo "+++ :terraform: Terraform Plan"
#terraform plan -var-file=vars/${TARGET_ACCOUNT_NAME}.tfvars -out=tfplan-${TARGET_ACCOUNT_NAME}
terraform plan -out=tfplan-test

echo "finished the plan"

echo "+++ :terraform: Terraform Init"
terraform init \
    -backend-config="bucket=terraform-tfstate-elaheh"
echo "+++ :terraform: Terraform Apply"
terraform apply tfplan-test

echo "finished the apply"